// Minimal placeholder PDF generator using pdf-lib. Each PDF is a single page
// with the title + a "DEMO SEED — fictional data" disclaimer.

import { PDFDocument, StandardFonts, rgb } from "npm:pdf-lib@1.17.1";

export async function makePlaceholderPdf(title: string, subtitle: string): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]); // A4
  const font = await pdf.embedFont(StandardFonts.HelveticaBold);
  const body = await pdf.embedFont(StandardFonts.Helvetica);

  page.drawText("DEMO SEED — FICTIONAL DATA", {
    x: 50, y: 800, size: 10, font: body, color: rgb(0.6, 0.1, 0.1),
  });
  page.drawText(title, { x: 50, y: 740, size: 22, font, color: rgb(0.1, 0.2, 0.15) });
  page.drawText(subtitle, { x: 50, y: 710, size: 12, font: body, color: rgb(0.3, 0.3, 0.3) });
  page.drawText("This is a placeholder document generated by the LegacyBuilder", {
    x: 50, y: 660, size: 11, font: body, color: rgb(0.2, 0.2, 0.2),
  });
  page.drawText("demo seeding edge function. Not a real legal record.", {
    x: 50, y: 645, size: 11, font: body, color: rgb(0.2, 0.2, 0.2),
  });
  page.drawText(`Generated: ${new Date().toISOString()}`, {
    x: 50, y: 80, size: 9, font: body, color: rgb(0.5, 0.5, 0.5),
  });

  return await pdf.save();
}
